### ISSUE TITLE
'gbk' codec can't decode byte 0xa8 in position 

### ISSUE THREAD

**Issue by brucehsie** [lux-org/lux-widget#68]
**C:\Users\86186> jupyter labextension install luxwidget**
Building jupyterlab assets (build:prod:minimize)
\Exception in thread Thread-8:
Traceback (most recent call last):
  File "D:\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\lib\subprocess.py", line 1366, in _readerthread
    buffer.append(fh.read())
**UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 11747: illegal multibyte sequence**
An error occured.
IndexError: list index out of range
See the log file for details:  C:\Users\86186\AppData\Local\Temp\jupyterlab-debug-w838bc84.log

**Comment by dorisjlee** [comment]
Hi @brucehsie, Thanks for your question. Were you able to successfully run: 
```python
jupyter labextension install @jupyter-widgets/jupyterlab-manager
``` 
and 
```python
 pip install lux-api
```
before running `jupyter labextension install luxwidget`?
